on: 
  push:
    branches:
      - main
name: Build, Bundle & Deploy
jobs:
  build-bundle-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      # Build static pages w/ Zola
      - name: Build ğŸ—ï¸
        uses: TonySpegel/zola-build-action@v1.0.1
        env:
          CONFIG_FILE: "config.live.toml"
      # Install NPM dependencies & bundle w/ Rollup
      - name: Bundle ğŸ§¶
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build-rollup-live
      # Deploy to GitHub Pages
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.          